### ISSUE TITLE
Request entity not found

### ISSUE THREAD

**Issue by pmast** [google/fusion-tables-drive-export#1]
Exporting one or many fusion tables returns an error:

"Error! Requested entity was not found."

Reported by @briandavidthom

I have experienced the same issue. It does not depend on different tables. All tables are covered.
It happens after a long spinner, not our regular progress screen.
My guess is that has to do with the fusion tables API or the drive API.

**Comment by pmast** [comment]
Hm, the message `Requested entity was not found` is thrown by fire base. Might be an issue there?

**Comment by pmast** [comment]
It seems the error occurs when there is already an `ft-archive` folder created form a different application.

Possible solution:
include the creater (the app that created the folder) in this query:
https://github.com/google/fusion-tables-drive-export/blob/master/server-src/drive/find-file.ts#L49

**Comment by pmast** [comment]
Question remains: why do we get an error form datastore?
We should fix that as well.

**Comment by pmast** [comment]
Additional info from Russel:

> One of the OAuth scopes is that the tool can write to files that this particular OAuth client has created... I had to switch cloud projects at one point (remember the app was not deploying) and so the OAuth client changed.
And the new client cannot write to the sheet ft-archive-index that the old client had created.
> 
> The solution is to rename the existing sheet from ft-archive-index to <anything-else>.

**Comment by hundekoerper** [comment]
The error isn't thrown by datastore. It's the error message of a 404 error from the sheets API.
